apiVersion: v1
kind: Pod
metadata:
  name: static-spongebob
  labels:
    role: discord-bot
spec:
  containers:
      - name: sponge-exe
        image: jrabbit/spongebob_exe
        volumeMounts: 
            - name: discord
              mountPath: "/etc/spongebob_exe"
              readOnly: true
  volumes:
    - name: discord
      secret:
          secretName: sponge-sec-discord